refactor(release): Redid retrieval of tag logic

diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -26,7 +26,12 @@ jobs:
         id: tag
         run: |
           git fetch --tags
-          echo "tag=$(git tag --sort=-v:refname | tail -n 1)" >> $GITHUB_OUTPUT
+          tag=$(git tag --points-at HEAD | head -n 1)
+          if [ -z "$tag" ]; then
+            echo "::error ::No tag found on current commit. Aborting release."
+            exit 1
+          fi
+          echo "tag=$tag" >> $GITHUB_OUTPUT
 
       - name: Read changelog
         id: changelog
