fix(release): Change the tag sorting logic

diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -26,7 +26,11 @@ jobs:
         id: tag
         run: |
           git fetch --tags
-          latest_tag=$(git tag --sort=-v:refname | grep '^v' | tail -n 1)
+          latest_tag=$(git tag --sort=-v:version | grep '^v' | head -n 1)
+          if [ -z "$latest_tag" ]; then
+            echo "::error ::No version tag found."
+            exit 1
+          fi
           echo "Latest tag: $latest_tag"
           echo "tag=$latest_tag" >> $GITHUB_OUTPUT
 
